pipeline {
        agent any
        stages {

            stage('Build and Test') {
                steps {
                    dir(workspace) {
                        sh 'mvn clean test'
                    }
                }
            }
            stage('Package') {
                steps {
                    dir(workspace) {
                        sh 'mvn package -DskipTests'
                    }
                }
            }
            stage('Build Docker Image') {
                steps {
                    dir(workspace) {
                        sh 'sudo docker compose up -d --build'
                    }
                }
            }
        }
        post {
            always {
                echo 'Cleaning up workspace'
                cleanWs()
            }
        }
    }