pipeline {
        agent any
        stages {

            stage('Build and Test') {
                steps {
                    dir(workspace) {
                        sh 'docker exec pricing-service mvn clean test'
                    }
                }
            }
            stage('Package') {
                steps {
                    dir(workspace) {
                        sh 'docker exec pricing-service mvn package -DskipTests'
                    }
                }
            }
            stage('Build Docker Image') {
                steps {
                    dir(workspace) {
                        sh 'docker build -t pricing-service:latest .'
                    }
                }
            }
        }
        post {
            always {
                echo 'Cleaning up workspace'
                cleanWs()
            }
        }
    }